"use client";import {useEffect,useState} from "react";import Link from "next/link";import {ChevronLeft,ChevronRight,Pause,Play} from "lucide-react";
const slides=[
 ["CUSTOM GARMENTS","Hoodies, T-shirts, jackets, tracksuits, jerseys and gymwear.","https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1800&q=85"],
 ["FOOTBALL / SOCCER","Custom footballs, match kits and training equipment.","https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1800&q=85"],
 ["CRICKET","Bats, balls, batting gloves, pads and complete team kits.","https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1800&q=85"],
 ["HOCKEY","Sticks, balls, uniforms and protective equipment.","https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?auto=format&fit=crop&w=1800&q=85"],
 ["BASKETBALL","Custom balls, jerseys and performance equipment.","https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1800&q=85"],
 ["BOXING & FITNESS","Boxing gloves, training equipment and technical apparel.","https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1800&q=85"],
 ["PRIVATE LABEL","One partner for custom garments and sporting goods.","https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1800&q=85"]
] as const;
export default function Hero(){const [i,setI]=useState(0),[paused,setPaused]=useState(false);useEffect(()=>{if(paused)return;const t=setInterval(()=>setI(v=>(v+1)%7),6000);return()=>clearInterval(t)},[paused]);const go=(n:number)=>setI((n+7)%7);return <section className="relative h-[72vh] min-h-[580px] overflow-hidden bg-navy text-white" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} aria-roledescription="carousel" aria-label="Product capabilities"><div className="absolute inset-0 bg-cover bg-center transition-all duration-700" style={{backgroundImage:`url('${slides[i][2]}')`}}/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/70 to-navy/10"/><div className="container-x relative flex h-full items-center"><div className="max-w-3xl"><p className="eyebrow">Made to your specification · Exported worldwide</p><h1 className="display mt-4 text-6xl leading-[.92] sm:text-7xl lg:text-8xl">{slides[i][0]}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/80">{slides[i][1]}</p><p className="mt-4 text-sm font-bold tracking-[.16em]">YOUR DESIGN. YOUR QUANTITY. YOUR PRICE.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn btn-orange" href="/request-quote">Request a quote</Link><Link className="btn btn-outline" href={i===0||i===6?"/custom-garments":"/sports-equipment"}>Explore products</Link></div></div></div><button onClick={()=>go(i-1)} className="absolute bottom-8 right-24 grid h-12 w-12 place-items-center border border-white/40 hover:bg-white hover:text-navy" aria-label="Previous slide"><ChevronLeft/></button><button onClick={()=>go(i+1)} className="absolute bottom-8 right-8 grid h-12 w-12 place-items-center border border-white/40 hover:bg-white hover:text-navy" aria-label="Next slide"><ChevronRight/></button><div className="absolute bottom-8 left-1/2 hidden -translate-x-1/2 items-center gap-2 sm:flex">{slides.map((s,n)=><button key={s[0]} onClick={()=>go(n)} aria-label={`Go to slide ${n+1}: ${s[0]}`} className={`h-2 transition-all ${i===n?"w-8 bg-orange":"w-2 bg-white/50"}`}/>) }<button onClick={()=>setPaused(!paused)} className="ml-3" aria-label={paused?"Play slideshow":"Pause slideshow"}>{paused?<Play size={16}/>:<Pause size={16}/>}</button></div></section>}
